// <auto-generated />
using System;
using KDramaSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KDramaSystem.Infrastructure.Migrations
{
    [DbContext(typeof(KDramaDbContext))]
    partial class KDramaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Atividades", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Ator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Altura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("AnoNascimento")
                        .HasColumnType("integer");

                    b.Property<string>("Biografia")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Atores", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecomendadoPorNomeLivre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RecomendadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avaliacoes", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TemporadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Dorama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("integer");

                    b.Property<bool>("EmExibicao")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagemCapaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Plataforma")
                        .HasColumnType("integer");

                    b.Property<string>("Sinopse")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloOriginal")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Doramas", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.DoramaAtor", b =>
                {
                    b.Property<Guid>("DoramaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtorId")
                        .HasColumnType("uuid");

                    b.HasKey("DoramaId", "AtorId");

                    b.HasIndex("AtorId");

                    b.ToTable("DoramaAtores", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.DoramaLista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoramaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListaPrateleiraId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ListaPrateleiraId");

                    b.ToTable("DoramasListas", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Episodio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Sinopse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("Episodios", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoramaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DoramaId");

                    b.ToTable("Generos", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.ListaPrateleira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImagemCapaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Privacidade")
                        .HasColumnType("integer");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ListasPrateleiras", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.ProgressoTemporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EpisodiosAssistidos")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemporadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.HasIndex("UsuarioId", "TemporadaId")
                        .IsUnique();

                    b.ToTable("ProgressoTemporadas", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Temporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("integer");

                    b.Property<Guid>("DoramaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EmExibicao")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Sinopse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DoramaId");

                    b.ToTable("Temporadas", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.UsuarioAutenticacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UsuariosAutenticacao", (string)null);
                });

            modelBuilder.Entity("UsuarioRelacionamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeguidorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeguindoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeguindoId");

                    b.HasIndex("SeguidorId", "SeguindoId")
                        .IsUnique();

                    b.ToTable("UsuarioRelacionamentos", (string)null);
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Atividade", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Usuario", null)
                        .WithMany("Atividades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KDramaSystem.Domain.ValueObjects.TipoAtividade", "Tipo", b1 =>
                        {
                            b1.Property<Guid>("AtividadeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Valor")
                                .HasColumnType("integer")
                                .HasColumnName("TipoAtividade");

                            b1.HasKey("AtividadeId");

                            b1.HasIndex("Valor");

                            b1.ToTable("Atividades", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AtividadeId");
                        });

                    b.Navigation("Tipo")
                        .IsRequired();
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Usuario", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KDramaSystem.Domain.ValueObjects.ComentarioValor", "Comentario", b1 =>
                        {
                            b1.Property<Guid>("AvaliacaoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Comentario");

                            b1.HasKey("AvaliacaoId");

                            b1.ToTable("Avaliacoes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AvaliacaoId");
                        });

                    b.OwnsOne("KDramaSystem.Domain.ValueObjetcs.Nota", "Nota", b1 =>
                        {
                            b1.Property<Guid>("AvaliacaoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Valor")
                                .HasColumnType("integer")
                                .HasColumnName("Nota");

                            b1.HasKey("AvaliacaoId");

                            b1.ToTable("Avaliacoes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AvaliacaoId");
                        });

                    b.Navigation("Comentario");

                    b.Navigation("Nota")
                        .IsRequired();
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Usuario", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KDramaSystem.Domain.ValueObjects.ComentarioValor", "Texto", b1 =>
                        {
                            b1.Property<Guid>("ComentarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Texto");

                            b1.HasKey("ComentarioId");

                            b1.ToTable("Comentarios", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ComentarioId");
                        });

                    b.Navigation("Texto")
                        .IsRequired();
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.DoramaAtor", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Ator", "Ator")
                        .WithMany("Doramas")
                        .HasForeignKey("AtorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KDramaSystem.Domain.Entities.Dorama", "Dorama")
                        .WithMany("Atores")
                        .HasForeignKey("DoramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Dorama");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.DoramaLista", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.ListaPrateleira", null)
                        .WithMany("Doramas")
                        .HasForeignKey("ListaPrateleiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Episodio", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Temporada", "Temporada")
                        .WithMany("Episodios")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Genero", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Dorama", null)
                        .WithMany("Generos")
                        .HasForeignKey("DoramaId");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.ListaPrateleira", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Usuario", null)
                        .WithMany("Listas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.ProgressoTemporada", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Temporada", "Temporada")
                        .WithMany()
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KDramaSystem.Domain.Entities.Usuario", null)
                        .WithMany("Progresso")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KDramaSystem.Domain.ValueObjects.StatusDorama", "Status", b1 =>
                        {
                            b1.Property<Guid>("ProgressoTemporadaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Valor")
                                .HasColumnType("integer")
                                .HasColumnName("Status");

                            b1.HasKey("ProgressoTemporadaId");

                            b1.ToTable("ProgressoTemporadas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProgressoTemporadaId");
                        });

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("Temporada");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Temporada", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Dorama", "Dorama")
                        .WithMany("Temporadas")
                        .HasForeignKey("DoramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dorama");
                });

            modelBuilder.Entity("UsuarioRelacionamento", b =>
                {
                    b.HasOne("KDramaSystem.Domain.Entities.Usuario", "Seguidor")
                        .WithMany("Seguindo")
                        .HasForeignKey("SeguidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KDramaSystem.Domain.Entities.Usuario", "Seguindo")
                        .WithMany("Seguidores")
                        .HasForeignKey("SeguindoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seguidor");

                    b.Navigation("Seguindo");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Ator", b =>
                {
                    b.Navigation("Doramas");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Dorama", b =>
                {
                    b.Navigation("Atores");

                    b.Navigation("Generos");

                    b.Navigation("Temporadas");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.ListaPrateleira", b =>
                {
                    b.Navigation("Doramas");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Temporada", b =>
                {
                    b.Navigation("Episodios");
                });

            modelBuilder.Entity("KDramaSystem.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Comentarios");

                    b.Navigation("Listas");

                    b.Navigation("Progresso");

                    b.Navigation("Seguidores");

                    b.Navigation("Seguindo");
                });
#pragma warning restore 612, 618
        }
    }
}
